services:
  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./gateway.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks: [app404]

  web:
    build:
      context: ..
      dockerfile: team3/Dockerfile
    environment:
      - TEAM_NAME=team3
    networks: [app404]
    command: >
      sh -c "
       python manage.py migrate --database=team3 &&
       python manage.py migrate team3 --database=team3 &&
       python manage.py runserver 0.0.0.0:8000
       "
    volumes:
      - ../:/app
    working_dir: /app

networks:
  app404:
    external: true
    name: app404_net
